### Ordinal-Encoding- use kora hoy input side e jodi high-medium-low ei typer er data thake tahole

### level-Encoding- Use kora hoy traget part e .

In [46]:
import numpy as np
import pandas as pd

In [47]:
df = pd.read_csv('customer.csv')
df.sample(5)

age  gender   review education purchased
42   30  Female     Good        PG       Yes
43   27    Male     Poor        PG        No
19   97    Male     Poor        PG       Yes
10   98  Female     Good        UG       Yes
24   16  Female  Average        PG       Yes

# hisabe er subidharthe kichu Column bad diye dilam 

In [48]:
df = df.iloc[:,2:]
df.head()

review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [49]:
from sklearn.model_selection import train_test_split
X_train , X_test ,y_train, y_test = train_test_split(df.iloc[:,0:2],df.iloc[:,-1],test_size=0.2)

In [50]:
X_train

review education
19     Poor        PG
28     Poor    School
17     Poor        UG
24  Average        PG
22     Poor        PG
47     Good        PG
41     Good        PG
42     Good        PG
36     Good        UG
37  Average        PG
39     Poor        PG
32  Average        UG
5   Average    School
8   Average        UG
21  Average        PG
11     Good        UG
26     Poor        PG
40     Good    School
48     Good        UG
31     Poor    School
43     Poor        PG
6      Good    School
4   Average        UG
45     Poor        PG
33     Good        PG
9      Good        UG
7      Poor    School
2      Good        PG
3      Good        PG
16     Poor        UG
25     Good    School
44  Average        UG
30  Average        UG
1      Poor        UG
15     Poor        UG
46     Poor        PG
10     Good        UG
35     Poor    School
13  Average    School
20  Average    School

## Apply OrdinalEncoder

In [51]:
from sklearn.preprocessing import OrdinalEncoder

In [52]:
X_train

review education
19     Poor        PG
28     Poor    School
17     Poor        UG
24  Average        PG
22     Poor        PG
47     Good        PG
41     Good        PG
42     Good        PG
36     Good        UG
37  Average        PG
39     Poor        PG
32  Average        UG
5   Average    School
8   Average        UG
21  Average        PG
11     Good        UG
26     Poor        PG
40     Good    School
48     Good        UG
31     Poor    School
43     Poor        PG
6      Good    School
4   Average        UG
45     Poor        PG
33     Good        PG
9      Good        UG
7      Poor    School
2      Good        PG
3      Good        PG
16     Poor        UG
25     Good    School
44  Average        UG
30  Average        UG
1      Poor        UG
15     Poor        UG
46     Poor        PG
10     Good        UG
35     Poor    School
13  Average    School
20  Average    School

In [53]:
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])
oe

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [54]:
oe.fit(X_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [55]:
X_train = oe.transform(X_train)


In [56]:
X_train 

array([[0., 2.],
       [0., 0.],
       [0., 1.],
       [1., 2.],
       [0., 2.],
       [2., 2.],
       [2., 2.],
       [2., 2.],
       [2., 1.],
       [1., 2.],
       [0., 2.],
       [1., 1.],
       [1., 0.],
       [1., 1.],
       [1., 2.],
       [2., 1.],
       [0., 2.],
       [2., 0.],
       [2., 1.],
       [0., 0.],
       [0., 2.],
       [2., 0.],
       [1., 1.],
       [0., 2.],
       [2., 2.],
       [2., 1.],
       [0., 0.],
       [2., 2.],
       [2., 2.],
       [0., 1.],
       [2., 0.],
       [1., 1.],
       [1., 1.],
       [0., 1.],
       [0., 1.],
       [0., 2.],
       [2., 1.],
       [0., 0.],
       [1., 0.],
       [1., 0.]])

In [58]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [59]:
X_train

array([[0., 2.],
       [0., 0.],
       [0., 1.],
       [1., 2.],
       [0., 2.],
       [2., 2.],
       [2., 2.],
       [2., 2.],
       [2., 1.],
       [1., 2.],
       [0., 2.],
       [1., 1.],
       [1., 0.],
       [1., 1.],
       [1., 2.],
       [2., 1.],
       [0., 2.],
       [2., 0.],
       [2., 1.],
       [0., 0.],
       [0., 2.],
       [2., 0.],
       [1., 1.],
       [0., 2.],
       [2., 2.],
       [2., 1.],
       [0., 0.],
       [2., 2.],
       [2., 2.],
       [0., 1.],
       [2., 0.],
       [1., 1.],
       [1., 1.],
       [0., 1.],
       [0., 1.],
       [0., 2.],
       [2., 1.],
       [0., 0.],
       [1., 0.],
       [1., 0.]])

## Apply LabelEncoder

In [60]:
from sklearn.preprocessing import LabelEncoder

In [61]:
le = LabelEncoder()

In [63]:
le.fit(y_train)

LabelEncoder()

In [64]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [65]:
y_train = le.transform(y_train)
y_test = le.transform(y_test)
y_train

array([1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1])